### ISSUE TITLE
Missing author ID field in response from endpoint that retrieving all comments for a given task.

### ISSUE THREAD

**Issue by HurasAdam** [Ewa-Anna/React-Django-Task-Tracker#132]
Currently, response from the comments list endpoint (http://127.0.0.1:8000/task-tracker/v1/task/comment-for-tasks/25)  missing "ID" field for the created_by object. This field is necessary for identifying users associated with each comment.
![commentsResponse](https://github.com/Ewa-Anna/React-Django-Task-Tracker/assets/103382498/c80ceb39-164f-460e-8551-890dc0c76915)

**Comment by Ewa-Anna** [comment]
Pull request #134 
![image](https://github.com/Ewa-Anna/React-Django-Task-Tracker/assets/99288124/5ac517a8-f1f2-4a08-8bc2-aaf18d096c12)
