### ISSUE TITLE
Implement Filtering Functionality for User List

### ISSUE THREAD

**Issue by HurasAdam** [Ewa-Anna/React-Django-Task-Tracker#138]
We need to Implement filtering capabilities for the list of users. (/task-tracker/v1/user/users/)

**Comment by Ewa-Anna** [comment]
When using parameter 'query':
` 127.0.0.1:8000/task-tracker/v1/user/users/?query=test `

The endpoint will return all matches that first_name **or** last_name contains 'test', eg.
![image](https://github.com/Ewa-Anna/React-Django-Task-Tracker/assets/99288124/1d99222b-9732-41ce-9d5a-48659b00b070)


Pull request #141
